### Получение событий

GET localhost:8080/api/events

### Добавление события

POST localhost:8080/events
Content-Type:application/json

{
"title":"Ferien",
"startDate":"2023-07-28",
"endDate":"2023-09-10"
}

### Получение одного события

GET localhost:8080/api/events/6

### Обновление события
 PUT localhost:8080/api/events/7
Content-Type: application/json

{
  "title" : "Отпуск",
  "startDate": "2023-12-22",
  "endDate": "2024-01-06"
}